### ISSUE TITLE
Automated packaging where stp file would be larger than 2gb fails in Powershell 5.1

### ISSUE THREAD

**Issue by Leodesk** [Numecent/Automated-Packaging#11]
Automated packaging where stp file would be large than 2gb fail in Powershell 5.1.
Studio version used: 9.3.1.1373 on Windows 10 with all Windows Updates, Powershell version 5.1
Application tested: Fusion 360 using latest admin installer.
When the studio-nip.ps1 script processes the function: Get-RevNote and the stp file is reopenend to add the RevNotes.txt file, the Compress-Archive command fails as this does not seem to support files over 2GB.
There is no stp file in the output folder.
The script works fine when the FinalizeIntoSTP is set to: false

The error in the console (note the last line):

```
New-Object : Exception calling ".ctor" with "3" argument(s): "Oppføringer som er større enn 4 GB, støttes ikke i oppdat
eringsmodus."
At C:\WINDOWS\system32\WindowsPowerShell\v1.0\Modules\Microsoft.PowerShell.Archive\Microsoft.PowerShell.Archive.psm1:73
2 char:23
+ ... ipArchive = New-Object -TypeName System.IO.Compression.ZipArchive -Ar ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [New-Object], MethodInvocationException
    + FullyQualifiedErrorId : ConstructorInvokedThrowException,Microsoft.PowerShell.Commands.NewObjectCommand

Rename-Item : Cannot rename because item at 'C:\NIP_software\Fusion 360\Output\Fusion360_2-0-16761_64bit_Online_Eng_Rel
1.zip' does not exist.
At C:\NIP_Software\studio-nip.ps1:219 char:5
+     Rename-Item -Path $zipFile -NewName $stpName
+     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Rename-Item], PSInvalidOperationException
    + FullyQualifiedErrorId : InvalidOperation,Microsoft.PowerShell.Commands.RenameItemCommand

Completed packaging successfully...
```

I first modified the script to just add the RevNotes.txt file to the output folder instead of the stp file if the file is over 2GB in size.
Seems the Compress-Archive has a fix but this is still in Preview: https://github.com/PowerShell/Microsoft.PowerShell.Archive/releases
Also tested with Powershell 7.3 which is a seperate download/install, there the script completes sucessfully and stp is created with revnotes.txt.
Maybe Powershell 7.3(pwsh.exe) as a requirement?

**Comment by TC-CoulsonLogic** [comment]
@Leodesk I've added a simple check to exclude attempting addition of the rev notes when the output file is above 2gb.  Not perfect, but as you say Compress-Archive is at fault so without enforcing use of another zip program or newer version of Compress-Archive it may fail. I may expand the check in the future to cater for where it would be supported.
