### ISSUE TITLE
Missing comma separator IrfanView JSON

### ISSUE THREAD

**Issue by maisyk** [Numecent/Automated-Packaging#4]
Hey Guys, 

Line 33 in the .json file linked below requires a comma at the end of it: 

https://github.com/Numecent/Automated-Packaging/blob/master/IrfanView/IrfanView_Packaging_Config_File.json

Change this:
"%winDir%\\Installer\\*.msi"

To this:
"%winDir%\\Installer\\*.msi",

Thanks, 
Umais

**Comment by maisyk** [comment]
Currently the Packaging NIP will pause if an error is detected in the JSON file. Maybe it will be a good idea to place this in a try/ catch and have the packaging script just throw an error opposed to stopping for user input to continue. 

This will be very helpful especially in our case where we plan on running the packaging script against multiple applications over night. 

Thanks, 
Umais

**Comment by giovanniolivera** [comment]
@maisyk the team has updated the script to prevent it from stopping at errors, can you please give it a try and let us know?
