### ISSUE TITLE
Studio-nip.ps1 applies incorrect setting

### ISSUE THREAD

**Issue by giovanniolivera** [Numecent/Automated-Packaging#5]
When using Automated Packaging, Studio is incorrectly setting the "IncludeSystemInstallationProcesses" setting to false by default. This might not be a problem on its own. However, the issue is that this setting was supposed to be a JSONv1.1 only setting, but it is incorrectly being set on JSONv1.

This is an issue because we have sample JSONv1's templates in our GitHub, and this new PS1 breaks those templates. The workaround is to add "IncludeSystemInstallationProcesses" = false to the JSONv1, but this creates confusion for our customers because our templates no longer work out of the box.

 

This request is to have the studio-nip.ps1 ignore (and not set) any "IncludeSystemInstallationProcesses" actions, unless the JSON is v1.1 or newer. We should probably also consider having the default be true rather than false, as it's the most common for packaging most apps.

**Comment by dpfiffner** [comment]
Resolved in update af1548f6b000e1abfcb6f2458d5356e38465fb5c on Dec 19th.
