### ISSUE TITLE
ModifyKeys not working

### ISSUE THREAD

**Issue by giovanniolivera** [Numecent/Automated-Packaging#6]
If AddFiles isn't populated in a JSON, then ModifyKeys will not work to create the .reg files, nor capture them into the appset. Verified that on line 234, "AddFiles" should be "ModifyKeys". Once changed, I successfully tested a JSON without "AddFiles" to work both creating and capturing the reg import action into the appset. To confirm I am not breaking  the"AddFile" feature, I've tested a JSON with both "AddFiles" and "ModifyKeys"

**Comment by dpfiffner** [comment]
Fixed in update aae7803.
